### ISSUE TITLE
Add exmple gif to readme

### ISSUE THREAD

**Issue by albinekb** [slammayjammay/hyper-postprocessing#1]
First, WOW I love this idea! Really cool and shows off the power of Hyper and the web. I am maintainer of zeit/hyper, if you need anything from us please let me know 🙏 

I think it would be nice to add something like this to show off possible things you can do with `hyper-postprocessing`

![kapture 2018-04-27 at 11 12 56](https://user-images.githubusercontent.com/5027156/39354876-f2af16ee-4a0b-11e8-92e4-37f2067fdb6c.gif)

**Comment by slammayjammay** [comment]
Thanks! I will definitely do that when I have some effects to demo.

**Comment by slammayjammay** [comment]
Posting gifs here so they're not held in the repo.

![glitch](https://user-images.githubusercontent.com/11801881/40855038-1dce9a88-6588-11e8-9f3a-ec552faf0631.gif)
![underwater](https://user-images.githubusercontent.com/11801881/40855040-200a1b60-6588-11e8-8cd7-adffdb6482e3.gif)
![film](https://user-images.githubusercontent.com/11801881/40855043-2196500c-6588-11e8-8d00-79df78abeece.gif)
![fallout-boy](https://user-images.githubusercontent.com/11801881/40855047-23c12546-6588-11e8-92a4-13d475afc5cd.gif)

**Comment by slammayjammay** [comment]
https://im5.ezgif.com/tmp/ezgif-5-2093014f6540.gif

**Comment by slammayjammay** [comment]
![cool-retro-term](https://user-images.githubusercontent.com/11801881/61190318-49112b80-a64f-11e9-806d-0dc89f73d70c.gif)
