### ISSUE TITLE
Glow on space-travel not there

### ISSUE THREAD

**Issue by andymule** [slammayjammay/hyper-postprocessing#11]
Everything works great! But the glow on the space-travel isn't there, suggesting either something broke in new builds (i'm on app-3.0.0-canary4) or the preview gif doesn't match the actual effect

![image](https://user-images.githubusercontent.com/1566594/51328830-82882600-1a74-11e9-87a8-44ce880118c7.png)

**Comment by slammayjammay** [comment]
Updated the example and the README gif
