### ISSUE TITLE
Shader not displaying on Hyper

### ISSUE THREAD

**Issue by michaelcavallaro03** [slammayjammay/hyper-postprocessing#14]
Hi there,

Great job on this, it looks awesome and I am really excited to get it working!

However I am experiencing some setup issues. I have tried all of the examples and receive the same issues (not being rendered).

I have tried a number of things. Including, installing `three` and `postprocessing` globally and within `.hyper_plugins` and changing file path to relative and absolute.

**Hyper DevTools Console**:
```
(re)loading renderer plugins
index.html:35 total init time 185.99000000000004
```

**.hyper.js**
```
    // for advanced config flags please refer to https://hyper.is/#cfg
    hyperPostprocessing: {
      entry: '/Users/michaelcavallaro/.hyper-postprocessing.js'
    }
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: ["hyper-postprocessing"],
```

**.hyper-postprocessing.js Fallout Boy Shader**
```
const { readFileSync } = require('fs');
const { relative } = require('path');
const { TextureLoader, LinearFilter, Uniform } = require('three');
const { EffectPass, Effect } = require('postprocessing');

module.exports = ({ hyperTerm, xTerm }) => {
	// turn all colors that aren't black into white -- then we can multiply the
	// image against this to "shine" through only the text (setting the background
	// to black in the hyper config is required)
	const textEffect = new Effect(
		'textEffect',
		readFileSync(relative(`../.hyper-effects/glsl/black-and-white.glsl`)).toString()
	);

	// move background image left
	const backgroundEffect = new Effect(
		'backgroundEffect',
		readFileSync(relative(`../.hyper-effects/glsl/background-image.glsl`)).toString(),
		{
			uniforms: new Map([['backgroundImage', new Uniform(null)]]),
			defines: new Map([['motionX', '-0.1']]),
			blendFunction: 10 // multiply
		}
	);

	new TextureLoader().load(relative(`../.hyper-effects/images/fallout-boy.jpg`), texture => {
		texture.minFilter = LinearFilter;
		backgroundEffect.uniforms.get('backgroundImage').value = texture;
	});

	return { pass: new EffectPass(null, textEffect, backgroundEffect) };
};

```

**Comment by slammayjammay** [comment]
Thanks man! Got a few questions:
1) What version of hyper-postprocessing is logged to the devtools?
2) Do you see any other console warnings or errors?
3) When you say it's not being rendered, is it showing a blank black screen or your normal hyper terminal?

Also I just noticed now that the whole thing completely breaks when hyper is refreshed. This might explain some problems other people had...

**Comment by michaelcavallaro03** [comment]
@slammayjammay  Sorry for the late response, didn't expect you to get back so quickly! So thanks for the quick response! 

> I just noticed now that the whole thing completely breaks when hyper is refreshed. 

Could you explain this a bit more? Because I have been refreshing constantly to try and get it working haha

Also, I will add the version when I am home from work. But no console warnings or errors.

**Comment by slammayjammay** [comment]
Refreshing Hyper using CMD+SHIFT+R results in a JS error being thrown and the plugin not being used. It's still usable but doesn't have any effects. If you're constantly refreshing this would explain it for you, but you should see an error in the dev tools.

**Comment by michaelcavallaro03** [comment]
Whoops haha, so now should I just start fresh and avoid refreshing?

**Comment by slammayjammay** [comment]
Unfortunately yes, refreshing will likely cause the plugin to break :(. I opened an issue for it and I'll try to get around to fixing it soon though.

**Comment by slammayjammay** [comment]
Hey Michael, the refresh error is fixed in the latest version, 2.1.0. Try installing that and see if it works?

**Comment by ifasina** [comment]
@slammayjammay I'm having a similar problem on version 2.1.0. I've followed the instructions on the readme page. I'm running hyper 3 by the way.

**Comment by slammayjammay** [comment]
@ifasina I don't know what that color/transparency warning is about but "Cannot find module 'postprocessing'" means that your entry file `requires` postprocessing but you haven't installed it.

You can check if your dependencies are installed by just executing that file with node:
```sh
$ node path-to-entry-file.js
```
It will throw the same error if you are missing a dependency.

**Comment by ifasina** [comment]
Thanks, I was under the impression that hyper would install any dependencies for me. I'm now running into a new issue after solving the dependency one.

[https://i.imgur.com/diwwv0n.png](https://i.imgur.com/diwwv0n.png)

**Comment by michaelcavallaro03** [comment]
@slammayjammay I did a clean install  of Hyper, and installed the latest of your plugin. Upon setup I ran into that dependency issue you mentioned in the ReadMe so I tried installing globally. Which unfortunately gave the same error in Hyper Dev Tools.  Then i tried installing `three@0.103.0` and `postprocessing@6.2.1` as the read me suggest and the error went away in dev tools but the shader is not working. Worth noting that I tried what you suggested and running `node path-to-entry-file.js` and received the same output. 

```
Error: Cannot find module 'three'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/michaelcavallaro/.hyper_effects/fallout.js:3:50)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```
Again, I am trying to get just one of the examples working (Fallout).

**Comment by slammayjammay** [comment]
@michaelcavallaro03 I am not sure why `node path-to-entry-file.js` throws the error but it doesn't show up in dev tools. I think everything should work if you installed `three` and `postprocessing` under `/Users/michaelcavallaro/.hyper_effects/`.

Can you show what your directory setup is like? Is it something like this?
```
- /Users/michaelcavallaro/
  - .hyper_effects/
    - fallout.js     <-- entry file?
    - node_modules/
      - three
      - postprocessing
```

**Comment by michaelcavallaro03** [comment]
```
- /Users/michaelcavallaro/
  - .hyper_effects/
    - fallout.js     <-- entry file?
    - node_modules/
      - three
      - postprocessing

**Comment by michaelcavallaro03** [comment]
Woooooo!!! It worked! Thanks so much for your help @slammayjammay the struggle was well worth the end result! I'll open up a small PR for ReadMe changes if it helps!

**Comment by slammayjammay** [comment]
Nice, glad you could get it working!
