### ISSUE TITLE
Bad render on Windows 10

### ISSUE THREAD

**Issue by pevecyan** [slammayjammay/hyper-postprocessing#2]
Hi, I don't know if you are aware, but on Windows 10 if I scale hyper window to anything but minimum it renders in really bad quality (screenshot bellow).
Any ideas?

![image](https://user-images.githubusercontent.com/1165448/39395976-39476edc-4ae6-11e8-9503-e2e01bd1b6cf.png)

**Comment by slammayjammay** [comment]
Thanks -- should be [fixed](https://github.com/slammayjammay/hyper-postprocessing/commit/bfdc7d3d371cfaa4d48704b8c6e96dd1109f496d) now.
