### ISSUE TITLE
Performance drops with multiple tabs

### ISSUE THREAD

**Issue by marcofugaro** [slammayjammay/hyper-postprocessing#21]
Premise: I own a recent macbook pro.

I build by custom terminal with some cool shaders and stuff, and I noticed that performances were bad when I was using like 2-3 tabs in hyper.

So I've been using this plugin without any cool passes just to test raw three.js performance. 
Doing this, it starts to lag (~700ms on input) when I open 7 tabs. It even lags with 4-5 tabs if I leave hyper open for some time. I think this problem is amplified when using some postprocessing passes.

I think it's something to do with three.js needing to be optimized (sharing stuff?) to allow efficiently multiple renders at the same time. Or it might be some memory leak?

However looking at [your source code](https://github.com/slammayjammay/hyper-postprocessing/blob/9299fcebe25faff70235f3cd5ea341d3c6fd49ed/src/index.js#L347-L374) I can see you're doing everything correctly when switching tabs and disposing of the unused renderer. I couldn't think a way of doing it better.

Do you have any idea what might be the source of this? Does this happens to you also?

**Comment by slammayjammay** [comment]
I definitely used to see a huge input lag on multiple tabs a while ago, but just checked on my mac version 10.14 and there isn't much performance hit when 7+ tabs are open. There's definitely a problem when multiple windows are.

That code you linked, the `destroy` method, only gets called when a tab or window is closed. If there are multiple tabs open then there will be multiple three.js renderers, and only the renderer associated with the current tab will render. The rest won't do anything but they will still take up memory.

When you say you're using the plugin without any passes, how are you doing this? The plugin won't initialize anything three.js related if no passes are given. You can test if three.js is initialized by seeing if something like this is logged to the console:

```
THREE.WebGLRenderer 103
```

How does a vanilla Hyper behave for you? Do you see a performance hit when multiple tabs or windows are open? I don't.

Can you post your Mac, Hyper, and hyper-postprocessing versions?

**Comment by marcofugaro** [comment]
Oh so the renderer stays in the background when the tab is not active! I think that might be the cause of the lag issues.

I think here we should `destroy()` instead of just pausing the loop. And then restart everything.

https://github.com/slammayjammay/hyper-postprocessing/blob/9299fcebe25faff70235f3cd5ea341d3c6fd49ed/src/index.js#L223-L227

I'm gonna try this on my machine, and see if it solves the lag issues. Do you know how can I test a local version of `hyper-postprocessing` in my hyper?

----

I'm gonna give you more information about my lag issues as you asked.

- This is the mininal three.js setup in the `.hyper-postprocessing.js` I was referring to: 
```js
const { EffectPass } = require('./.hyper_plugins/node_modules/postprocessing')

module.exports = ({ hyperTerm, xTerm }) => {
  const effects = []

  return { pass: new EffectPass(null, ...effects) }
}
```

- Yes I see `THREE.WebGLRenderer` in the console

<img src="https://user-images.githubusercontent.com/7217420/63635299-94acf100-c661-11e9-94cd-877b0014ec5a.png" width="200">

and I'm using these versions of hyper and hyper postprocessing and macOS

<img src="https://user-images.githubusercontent.com/7217420/63635342-fe2cff80-c661-11e9-9c39-4013556b5733.png" width="250">


<img src="https://user-images.githubusercontent.com/7217420/63635321-ba39fa80-c661-11e9-8c09-05d2af5f4b66.png" width="300">


<img src="https://user-images.githubusercontent.com/7217420/63635350-100ea280-c662-11e9-9dda-f82c13e9fc22.png" width="320">


- Vanilla Hyper gives me no issues at all

- I didn't test it with multiple windows, we can't do much with that.
----

I've been doing some more testing, looks like the number of passes does not matter, the input lag happens both with the barebones example and the main `Cool Retro Term` effect.

I can reproduce my issue straight up opening 7 tabs, but as I said it happens also when I have opened 2-4 tabs during the day, which I usually do.

Here is a performance recording of when I have 7 tabs opened, you can just upload it in the `Performance` pane in the devtools. 

[7-tabs.json.zip](https://github.com/slammayjammay/hyper-postprocessing/files/3537101/7-tabs.json.zip)

Looks like the bottleneck is webgl's `texImage2D`, which sould be the part where an image is uploaded to the GPU.

**Comment by slammayjammay** [comment]
Thanks for the info. Read [this](https://hyper.is/#extensions-module-loading) and [this](https://github.com/zeit/hyper/blob/master/PLUGINS.md) to run local plugins. You will have to clone this repo inside your local plugins directory, make changes to the source code, build it, then restart Hyper to see changes.

Yeah each renderer just kinda sticks around forever until tabs are closed....I think it's possible to just create one threejs/postprocessing instance that applies for the entire window, rather than creating an entirely new instance for each tab. That'll probably fix your problem. Even if it doesn't it's better than having a bunch of garbage renderers just floating around doing nothing. I'll look into it when I have time.

**Comment by marcofugaro** [comment]
Thank you! I will take a stab at this when I can, and see if it fixes my problem. 

Yes! I'll try with the 1 renderer : multiple scenes approach, as described here

https://threejs.org/examples/?q=elements

https://threejsfundamentals.org/threejs/lessons/threejs-multiple-scenes.html

**Comment by slammayjammay** [comment]
Fixed in [v3](https://github.com/slammayjammay/hyper-postprocessing/releases/tag/v3.0.0)

**Comment by marcofugaro** [comment]
Thank you so much! Sorry I didn't find the time to update my PR. Will test the new version and let you know if there's still any performance issue!
