### ISSUE TITLE
Setup instructions not working in Hyper 3

### ISSUE THREAD

**Issue by daneeq** [slammayjammay/hyper-postprocessing#28]
Hi,

just found your plugin and tried to install it using the instructions in Readme, but I wasn't successful - the theme doesn't change after reload nor restart.

This is what I put in `.hyper.js` under `config`:
```
hyperPostprocessing: {
			// defaults to `${HOME}/.hyper-postprocessing.js`
			entry: '~/code/hyper/plugins/retro.js'
		}
```
as well as 
```
plugins: [
    'hyper-postprocessing'
  ],
```
as per the instructions. In the `retro.js` file, I simply copy-pasted your example [here](https://github.com/slammayjammay/hyper-postprocessing/blob/master/examples/effects/retro/index.js). I also tried it with the [quick-start.js](https://github.com/slammayjammay/hyper-postprocessing/blob/master/examples/quick-start.js) and with copying the file to the default location (`${HOME}/.hyper-postprocessing.js`), but nothing worked so far.

I'm using Hyper 3.0.2

Thanks,
Dan

**Comment by MrSiliconGuy** [comment]
On Windows, I am also having the same issue

Error Output:
`
[16312:0511/220041.878:INFO:CONSOLE(11)] "Error: Cannot find module 'postprocessing'", source: C:\Users\Bryan C\AppData\Roaming\Hyper\.hyper_plugins\node_modules\hyper-postprocessing\dist\built.js (11)

[16312:0511/220041.884:INFO:CONSOLE(11)] "Uncaught TypeError: Cannot read property 'passes' of undefined", source: C:\Users\Bryan C\AppData\Roaming\Hyper\.hyper_plugins\node_modules\hyper-postprocessing\dist\built.js (11)
`

It seems like the plugin has some sort of issue loading the module from the URL

Also using Hyper 3.0.2
Thanks

**Comment by slammayjammay** [comment]
@daneeq any errors or warnings in the console?

@MrSiliconGuy that error "Error: Cannot find module 'postprocessing'" looks like you need to install `three` and `postprocessing` in the directory of the entry file.

If you cd to the entry file directory and either or these these return empty, the plugin won't work.

```sh
npm ls three postprocessing
```

**Comment by MrSiliconGuy** [comment]
Alright I've switched over to linux for easier testing, with a fresh install of hyper.

I added `hyper-postprocessing` into the plugins, and copied the contents of [retro/index.js](https://github.com/slammayjammay/hyper-postprocessing/blob/master/examples/effects/retro/index.js)
to `~/.hyper-postprocessing.js`. The module `three` is imported before `postprocessing`

Running `hyper -v` gave the following output:
```
[15853:0512/085109.341872:INFO:CONSOLE(11)] "Error: Cannot find module 'three'", source: /home/bryan/.hyper_plugins/node_modules/hyper-postprocessing/dist/built.js (11)

[15853:0512/085109.342281:INFO:CONSOLE(11)] "Uncaught TypeError: Cannot read property 'passes' of undefined", source: /home/bryan/.hyper_plugins/node_modules/hyper-postprocessing/dist/built.js (11)
```

Trying [space-travel/index.js](https://github.com/slammayjammay/hyper-postprocessing/blob/master/examples/effects/space-travel/index.js) results in:

```
[16067:0512/085235.404588:INFO:CONSOLE(11)] "Error: Cannot find module 'postprocessing'", source: /home/bryan/.hyper_plugins/node_modules/hyper-postprocessing/dist/built.js (11)

[16067:0512/085235.405358:INFO:CONSOLE(11)] "Uncaught TypeError: Cannot read property 'passes' of undefined", source: /home/bryan/.hyper_plugins/node_modules/hyper-postprocessing/dist/built.js (11)
```

For this file, only `postprocessing` is imported. So clearly the problem seems to be with  `.hyper-postprocessing.js` importing files

And yes, it does look like `three` and `post-processing` are installed.
```
bryan@swift3:~$ ls ~/.hyper_plugins/node_modules
hyper-postprocessing  postprocessing  three
```

**Comment by MrSiliconGuy** [comment]
Alright, got it to work!

In `~/.hyper.js`, changed the config option to point to the js file in hyper-shaders
```
	config: {
		hyperPostprocessing: {
			entry: "/home/bryan/hyper-shaders/.hyper-postprocessing.js"
		}
	},
```

Made the folder `~/hyper-shaders` with everything necessary

```
bryan@swift3:~/hyper-shaders$ ls -A
glsl  .hyper-postprocessing.js  node_modules  package-lock.json
```

`.hyper-processing.js` contains [retro/index.js](https://github.com/slammayjammay/hyper-postprocessing/blob/master/examples/effects/retro/index.js)

With the line 
```
const fragmentShader = readFileSync(resolve(__dirname, '../../glsl/' + name + '.glsl')).toString();
```
modified to
```
const fragmentShader = readFileSync(resolve(__dirname, './glsl/' + name + '.glsl')).toString();
```
`glsl` contains all the stuff from the [glsl](https://github.com/slammayjammay/hyper-postprocessing/tree/master/examples/glsl) folder.
`node_modules` was created with `npm install three postprocessing` in `~/hyper-shaders`

[Result](https://imgur.com/bn7KpPR)

Overall seems like directly copying and pasting the files into `~/hyper-postprocessing.js` doesn't work, and requires a bit more setup. The README.md it isn't very clear about how to setup the shaders, and it looks like you have to include some stuff from the `examples/` folder.

And thanks for your time

**Comment by slammayjammay** [comment]
Great, glad you got it working. Yeah there is manual setup required to get the examples to work, which is not great. Maybe one day I will improve that.

**Comment by daneeq** [comment]
@slammayjammay yeah, sorry I didn't realize there was this option

Turns out there are a couple actually:
`WebGL2 is not supported on your machine. Falling back to canvas-based rendering.`
and
`Error: Cannot find module 'three'`

So I suppose this could be a bigger issue, if I potentially don't have any WebGL support on my machine?
