### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source?

### ISSUE THREAD

**Issue by NoviaDroid** [slammayjammay/hyper-postprocessing#30]
Hello, I followed the steps  in [https://github.com/slammayjammay/hyper-postprocessing/issues/27](https://github.com/slammayjammay/hyper-postprocessing/issues/27) but still failed to get it working.

And when open the developer tools, it says:

![image](https://user-images.githubusercontent.com/3263368/113899578-86442680-97ff-11eb-92af-c9f117ea205c.png)

**Comment by NoviaDroid** [comment]
Anyway I managed to fixed this issue by directly clone and use this config:

[https://github.com/BenjamienSD/hyperplugins/tree/master](https://github.com/BenjamienSD/hyperplugins/tree/master)

But still don't know why?

**Comment by slammayjammay** [comment]
Stumped. It looks like the error is being thrown inside the `three` dependency. So I'm wondering if it's not an issue with this repo.

**Comment by slammayjammay** [comment]
Fixed this with version 3.0.2 release. Depending on your Hyper version you can fix by installing hyper-postprocessing@3.0.2 or @4.0.0 (note in readme [here](https://github.com/slammayjammay/hyper-postprocessing#note))
