### ISSUE TITLE
Shader not being picked up - No error or warnings issued

### ISSUE THREAD

**Issue by moimart** [slammayjammay/hyper-postprocessing#4]
Hi,

I'm trying to setup a simple shader with a string and it does not seem to get picked up. I don't get any errors or warnings (neither in developer console nor in the app logging).

I'm attaching the shader and my config.

Thanks!

Br,
Moises
[files.zip](https://github.com/slammayjammay/hyper-postprocessing/files/2065779/files.zip)

**Comment by moimart** [comment]
Some progress on my side, I removed hyper-pane and it seems it's being picked now

**Comment by moimart** [comment]
Tried also on my non-dev hyper: hyper-pane creates the problem

**Comment by slammayjammay** [comment]
Yeah I looked into it and there's a [typo](https://github.com/chabou/hyper-pane/pull/28) in `hyper-pane` that potentially breaks other plugins. As a workaround I think you can just add `hyper-pane` to the bottom of your plugins array.

**Comment by chabou** [comment]
`hyper-pane` v2.1.3 with @slammayjammay's fix has been released.
Please update your plugins 😄

**Comment by moimart** [comment]
Thanks a lot guys!
