### ISSUE TITLE
Two quick questions, please excuse my ignorance

### ISSUE THREAD

**Issue by thedonquixotic** [slammayjammay/hyper-postprocessing#5]
2 Quick questions. 

1. The glow effect for the space travel one is contained in the fragment.js file, and if I wanted to just use the glow and not the space travel I could just call that file in the index.js and not call the space one correct?

2. It appears the glitch effect is being called from outside the index.js file in the example folder for that example? Is that.... like built into gsls or something? I'm sorry for my ignorance here, I'm not super familar with shaders, and have only the conceptual stuff that I've learned taking courses on Unity Shader Forge. I get the gist of it though, but looking at your code I don't see anything indicating the glitch effect, it just seems like it's being imported?

**Comment by thedonquixotic** [comment]
Ah.. okay I found the glitch shader here: https://github.com/vanruesc/postprocessing/blob/master/src/materials/GlitchMaterial.js

If I wanted to make it less extreme in it's effect would I just lower the numbers that it's being multiplied by?

Oooh wait I see this is being built off another thing called post-processing for three.js. Is there any ability to modify the level of the glitch effect without having to create my own fork etc?

**Comment by slammayjammay** [comment]
No problem.

1. Yup just remove `fragmentShader` from the returned array.

2. The glitch example uses 3 different effects: the actual glitch effect, a `DotScreen` effect, and a "curved monitor" effect. The fragment shader in that [example file](https://github.com/slammayjammay/hyper-postprocessing/blob/master/examples/glitch/index.js#L5-L39) file only does the "curved monitor" effect. The `Glitch` and `DotScreen` shaders live inside `postprocessing`.

It looks like you can't really adjust the numbers for the glitch effect -- they're being set directly on each render: https://github.com/vanruesc/postprocessing/blob/master/src/passes/GlitchPass.js#L171-L218

The only way you could would be to overwrite the `render` function which is sort of a pain. 
```js
```

**Comment by slammayjammay** [comment]
No problem.

1. Yup just remove `fragmentShader` from the returned array.

2. The glitch example uses 3 different effects: the actual glitch effect, a `DotScreen` effect, and a "curved monitor" effect. The fragment shader in that [example file](https://github.com/slammayjammay/hyper-postprocessing/blob/master/examples/glitch/index.js#L5-L39) file only does the "curved monitor" effect. The `Glitch` and `DotScreen` shaders live inside `postprocessing`.

It looks like you can't really adjust the numbers for the glitch effect -- they're being set directly on each render: https://github.com/vanruesc/postprocessing/blob/master/src/passes/GlitchPass.js#L171-L218

The only way you could would be to overwrite the render function which is sort of a pain. You would have to extend the GlitchPass class or something...

```js
/* `hyper-postprocessing` entry file */

const { GlitchPass } = require('postprocessing');

class ModifiedGlitchPass extends GlitchPass {
    render(renderer, inputBuffer, outputBuffer, delta, stencilTest) {
        // copy and paste the old render method here
        // https://github.com/vanruesc/postprocessing/blob/master/src/passes/GlitchPass.js#L171-L218
        // and then manually adjust the numbers yourself
    }
}

module.exports = {
    shaderPass: new ModifiedGlitchPass()
};
```

I don't know nearly enough about GLSL to know which numbers to adjust :( but you might start with the `amount` uniform. 

If that doesn't work out you could also try searching https://www.shadertoy.com for an effect you like. It will require a few tweaks to work with THREE.js but it might be a better option.

Hope that helps.

**Comment by thedonquixotic** [comment]
Rad yeah I saw that the screen curve was in the thing you were doing. I wasn't clear on how to modify the glitch effect. I might just take it out though and fiddle with it later once I learn more. Also I have an inkling I could get what I wanted by fiddling with the glow effect to maybe make a slight RGB offset. Maybe. I'm trying to replicate some of the look of the old Hyper 1 theme hyperpunk which used 3 animated text shadows to give a glitch like effect. 

Thanks you've been super helpful! This project looks awesome!

**Comment by slammayjammay** [comment]
Thanks man, best of luck to you!
