### ISSUE TITLE
Hey I was wondering if you might have a solution to this problem?

### ISSUE THREAD

**Issue by jcklpe** [slammayjammay/hyper-postprocessing#8]
Hey man! I'm finally back on the hyperjs plugin fiddling train. I was wondering if you might have a solution for this issue I'm having? https://github.com/zeit/hyper/issues/3267

Next step for me is to implement some shader stuff using this project. Glad to see you're still working on it! The chalk shader thing looks dope!

**Comment by slammayjammay** [comment]
Appreciate the kind words! I posted a possible solution over at that Hyper issue, hopefully it pertains to your particular situation. Good luck!
